In [2]:
import sys 
sys.path.append("../..") 
#sys.path.append("..") 
from malib.spaces import Discrete, Box, MASpace, MAEnvSpec

In [4]:
import numpy as np
np.asarray([1,2,4])

array([1, 2, 4])

In [14]:
action_spaces = MASpace(
            tuple(Discrete(3) for _ in range(5))
        )
Discrete(3).shape

()

In [16]:
observation_spaces = MASpace(
    tuple((Discrete(5)) for _ in range(5))
)
observation_spaces.shape

((), (), (), (), ())

In [87]:
observation_spaces = MASpace(
    tuple(Box(
            low = 0 , high=2, shape=(1,), dtype=np.int32
        ) for _ in range(5))
)
observation_spaces.shape

((1,), (1,), (1,), (1,), (1,))

In [98]:
observation_spaces[1].sample()

array([1], dtype=int32)

In [41]:
from multiagent.multi_discrete import MultiDiscrete
act_space = MultiDiscrete(
    [[0, 1,2]]
)

In [38]:
act_space.shape

1

In [39]:
print(act_space)

MultiDiscrete1


In [52]:
action_spaces = MASpace(
            tuple( MultiDiscrete([[0, 1,2]]) for _ in range(6))
        )
action_spaces[3].shape#[0]

1

In [102]:
np.array([4]).astype(np.float32)

array([4.], dtype=float32)

In [103]:
np.zeros((6,))

array([0., 0., 0., 0., 0., 0.])